### ISSUE TITLE
Error: ID token verification failed:

### ISSUE THREAD

**Issue by hrchu** [inrupt/generate-oidc-token#143]
Exception raised while login Inrupt Pod Spaces with this tool.

Reproduce:
<pre>
➜  workspace npx @inrupt/generate-oidc-token

? What Solid Identity Provider do you want to log in to? https://broker.pod.inrupt.com
? Has your app been pre-registered by the administrator of the Pod server you are signing in to? No.
? What is the name of the application you are registering? fghj
? @inrupt/generate-oidc-token will start a local web server, to which the Solid Identity Provider can redirect the user back after
 they log in. On what port do you want to run this server? 3001
</pre>

Log
<pre>
Listening at: [http://localhost:3001].
Logging in to Solid Identity Provider  https://broker.pod.inrupt.com to get a refresh token.

Please visit https://broker.pod.inrupt.com/authorization?client_id=pwv1sAW3tHpf6UNxkGFzDutuL6fnmpYm&scope=openid%20offline_access&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3001%2F&code_challenge=N9PMPYNssgIhGAHTtrjnEkrSWvZKLK3G6oTfjXJPjdE&state=4UztNNMRkzyGs4MMAjc2JbWL3O6Lcqv7dQ5Gnikqx3s&code_challenge_method=S256 in a web browser.

Login into the Identity Provider successful, receiving request to redirect IRI [http://localhost:3001/?code=Ing1X8htU4vWrdnyyEducffTJbOFHGEF&state=4UztNNMRkzyGs4MMAjc2JbWL3O6Lcqv7dQ5Gnikqx3s].
(node:1822) DraftWarning: The DPoP APIs implements an IETF draft. Breaking draft implementations are included as minor versions of the openid-client library, therefore, the ~ semver operator should be used and close attention be payed to library changelog as well as the drafts themselves.
(node:1822) UnhandledPromiseRejectionWarning: Error: ID token verification failed: JWSSignatureVerificationFailed: signature verification failed
    at flattenedVerify (/Users/petertc/.npm/_npx/7dfa8f34abd2be6f/node_modules/@inrupt/jose-legacy-modules/dist/index.js:2521:15)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async compactVerify (/Users/petertc/.npm/_npx/7dfa8f34abd2be6f/node_modules/@inrupt/jose-legacy-modules/dist/index.js:2554:22)
    at async Object.jwtVerify (/Users/petertc/.npm/_npx/7dfa8f34abd2be6f/node_modules/@inrupt/jose-legacy-modules/dist/index.js:2978:22)
    at async Object.getWebidFromTokenPayload (/Users/petertc/.npm/_npx/7dfa8f34abd2be6f/node_modules/@inrupt/solid-client-authn-core/dist/login/oidc/redirectHandler/IRedirectHandler.js:25:46)
    at async AuthCodeRedirectHandler.handle (/Users/petertc/.npm/_npx/7dfa8f34abd2be6f/node_modules/@inrupt/solid-client-authn-node/dist/login/oidc/redirectHandler/AuthCodeRedirectHandler.js:73:23)
    at async ClientAuthentication.handleIncomingRedirect (/Users/petertc/.npm/_npx/7dfa8f34abd2be6f/node_modules/@inrupt/solid-client-authn-node/dist/ClientAuthentication.js:58:34)
    at async Session.handleIncomingRedirect (/Users/petertc/.npm/_npx/7dfa8f34abd2be6f/node_modules/@inrupt/solid-client-authn-node/dist/Session.js:45:35)
    at async /Users/petertc/.npm/_npx/7dfa8f34abd2be6f/node_modules/@inrupt/generate-oidc-token/dist/index.js:85:9
    at Object.getWebidFromTokenPayload (/Users/petertc/.npm/_npx/7dfa8f34abd2be6f/node_modules/@inrupt/solid-client-authn-core/dist/login/oidc/redirectHandler/IRedirectHandler.js:32:15)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:1822) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1822) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
</pre>

**Comment by NSeydoux** [comment]
Hi @hrchu, thanks for reaching out. I could not reproduce the bug locally, could you try running `npx @inrupt/generate-oidc-token@latest` to ensure that we are running the same version ? I'll also ask the server team if some key rotation happened today which might have temporarily affected you.

**Comment by hrchu** [comment]
@NSeydoux thanks for your information. I ran `npx @inrupt/generate-oidc-token@latest` and got the same error message. Is there anything I can do to help diagnose this issue??

**Comment by hrchu** [comment]
I upgrade my node from v12 to v14 and the problem is solved. Thanks for your help!
